### PR TITLE
Fixing broken equations.

### PR DESCRIPTION
**Pull request by WPennock**
Removed .magnitude from functions, which were breaking units and enforced original units. Note: I have not tested all of these, but stripping units from parts of the functions, as was done originally when the functions were first written (no units used internally) is causing the majority of them to break.

### CODE REVIEW

**Comment by HannahSi** [comment]
Hi Will, thanks for catching these errors! It looks like the last time we updated this class, I commented out all the unit wrappers (`@u.wraps`) without also deleting the `.magnitudes`, which was useful only with the unit wrapper, so this was my bad.

Rather than enforcing units on the output though, we can specify the required units for inputs in the function specifications, so that the output will automatically have the correct units if the input requirements are met. (I've been updating `core.physchem` this way in the `hs649/function-wrappers` branch.) We'll also need to have the functions tested before releasing a new version. Since I've been doing the same for `physchem`, I can finish fixing `floc_model` if you'd like!

**Comment by WPennock** [comment]
Hi, Hannah;

Thank you for looking into this so quickly! I apologize if it was presumptuous to enforce units at the end, but I am not sure if there is any other way. For some of the functions, e.g., `pc_viscous`, I think the units will naturally become an agglomeration of all of the input units rather than `dimensionless`, as intended. I think enforcing units at the end also provides a check on the end result and also allows flexibility in the inputs used. So, because the calculations in `floc_model` are sometimes more complicated than those in `physchem`, I'm not sure the same approach should be used. Let me know what you think. Thank you so much for offering to work on the testing! I am a bit bogged down right now, and proposed this change because it has been hard not having this package working for my research.

**Comment by HannahSi** [comment]
Hi Will,

I want to apologize for taking so long to address this issue! Thank you for your work in fixing the broken equations. I agree now with how you enforced units at the end of functions. I'm sorry that the broken functions were a hindrance to your research, and again for delaying my testing while other urgent tasks came up in my AguaClara work. I understand this issue may no longer be relevant to your work. However, if you have some time, I would greatly appreciate if you could give some input on the following question. 

I have written tests for all the functions in `floc_model` except for `diam_floc_max` and `ener_dis_diam_floc`, because these were not dimensionally consistent, and I could not find the source of the underlying equation (except that it is from Ian Tse's research) to check the dimensions. The function comments also indicate that they are "under suspicion". Would you know where the equation is from? And if not, do you think they should be kept in the package?

**Comment by HannahSi** [comment]
Monroe and I agreed to deprecate `diam_floc_max` and `ener_dis_diam_floc` because the equation concluded from Tse's research is most likely not correct.

The functions from `floc_model` are therefore now fully tested!

**Review by HannahSi — APPROVED** [review]

**Review by ryan26192 — APPROVED** [review]

**Comment by WPennock** [comment]
Hi, Hannah!

I am likewise sorry it took me so long to respond. I've been in the process
of moving to and settling in India. I feel a bit more established now, so I
can start thinking about things like this again. Sorry I couldn't help with
the particular question about the Ian Tse equation, but I am so delighted
that everything is now tested with consistent units and no more unit
wrapper issues. Even though my dissertation is done, I hope to keep using
this codebase and encourage my future students to use it, as well. As I go,
I also hope to contribute more equations! So, thank you very much for
making this directly useable again; it means a lot!

I hope you are doing well and that your semester is wrapping up well. I
don't want to burden you with extra stuff right now, but I also have some
long promised updates I hoped to make to a few of the aguaclara modules.
Maybe in a few weeks I will follow up about how I can incorporate these.
Keep up the good work!
-*William Pennock*

**Pull request merged**
