### PR TITLE
Add Flocculator functionality

### PR DESCRIPTION
**Pull request by oliver-leung**
We've created a Python class for calculating all of the physical dimensions of the flocculator, as well as added some Sphinx autodocumentation.

If Sphinx works well, we'll try implementing it for the LFOM code as well.

### CODE REVIEW

**Comment by oliver-leung** [comment]
@HannahSi It looks like AppVeyor is failing with "Error: Secret passphrase is missing". Didn't we set it previously, or do we have to reconfigure it?

**Comment by HannahSi** [comment]
That's strange, we did fix the problem before by selecting the "Enable secure variables in Pull Requests from the same repository only" setting in Appveyor, and it looks like its passing again. Did you change anything just then to fix it again?

The code changes look alright to me. Are the RST files for the Sphinx documentation? I'm curious if there's a way to test them while they are on a non-master branch.

**Review by HannahSi — DISMISSED** [review]

**Comment by oliver-leung** [comment]
Hmm that's strange, I didn't do anything to make AppVeyor work again. I guess it's just a weird issue with AppVeyor?

The RST files are for the Sphinx documentation - they're text files, like Markdown. I don't think they can be tested, so I added an ignore statement in `codecov.yml` (unless you had something in mind for them?).

**Review by HannahSi — APPROVED** [review]
Actually, I think AppVeyor just takes longer to build, so I don't think it was improperly failing at all.

Everything else looks good, and it makes sense that we can just test the RST documentation by locally building it. Thanks for getting this auto-documentation started!

**Pull request merged**
