### PR TITLE
create a new release with version # 22

### PR DESCRIPTION
**Pull request by monroews**
This is my second attempt to create a new release with the updated code that is now already part of the master branch (but somehow wasn't released in the pip distribution of version 0.0.21). This pull request only changes the version number in setup.py

### CODE REVIEW

**Review by oliver-leung — DISMISSED** [review]
Looks good! You can go ahead and "squash and merge", then delete the branch.

For future reference, create a version branch like this *first* with the new version number, before you make any edits to the code. Then, merge code changes from other branches into the version branch, and merge the version branch into master.

**Comment by monroews** [comment]
I wasn't aware of this procedure of pushing to a version branch before merging to master. We need a step by step description of the process of submitting code and publishing it. That system needs to make it easy to fix bugs. When I discover bugs that are making it impossible for students to do their assignments there needs to be a more efficient way to make the fix. 

Would it be possible to approve this code so that the bugs in environmental processes can be fixed?

**Review by eak24 — APPROVED** [review]

**Comment by eak24** [comment]
@oliver-leung we shouldn't ever need to manually create a version branch. We should always be releasing master (the tests should ensure it is in a releasable state, as well as manual testing) and then the version branch will be created in the 'draft release' page like Monroe did. I think that implifies the process. At other companies, it is common to separate the 'release' and the 'deploy' phase so that we create a 'staging release' and then that undergoes rounds of manual testing and then we deploy. Our process isn't at that level (and it may never be), so I think straight deploys of master will work fine for us (and that is how travis is configured. @monroews I just approved and merged. I agree the process should be simple, and I think we should still require the review request approval - it's important that at least two people know what is happening at the moment of reckoning. Does that sound reasonable?

**Comment by oliver-leung** [comment]
@ethan92429 Yes, that sounds good! Apologies for not documenting this process - I'll make it a priority to write out the development cycle for contributors.

**Pull request merged**
