### PR TITLE
Update README to include testing instructions

### PR DESCRIPTION
**Pull request by eak24**

### CODE REVIEW

**Comment by eak24** [comment]
@monroews please confirm that you can run tests with the instructions I now included in the README. I just successfully followed them on a new box, but not on a Windows. Thanks!

**Review by monroews — APPROVED** [review]

**Comment by monroews** [comment]
The pip install directions don't work.

Here is what I typed in the github directory

pip install --user pipenv

*When I type *pipenv run pytest I get

'pipenv' is not recognized as an internal or external command,

operable program or batch file.


Monroe Weber-Shirk | Senior Lecturer

Phone: +1 (607) 216-8445  | mw24@cornell.edu



AguaClara Cornell | Safe Water on Tap

Cornell University | 265 Hollister Hall | Ithaca, NY 14853 |
AguaClara.cornell.edu <http://aguaclara.cee.cornell.edu/>

<http://aguaclara.cornell.edu/>

**Comment by eak24** [comment]
Hmm... Does that happen after you restart the shell? IT means that pipenv is not available on your command line, which might be a problem with your path setup... I'm guessing `where pipenv` returns nothing?

**Comment by eak24** [comment]
Try this answer: https://stackoverflow.com/questions/46041719/windows-reports-error-when-trying-to-install-package-using-pipenv It looks the most right!

**Comment by monroews** [comment]
These steps are missing from the readme

pip install --user pipenv

run the shell to activate the virtual environment
pipenv shell

Then you can run 
pipenv run pytest

**Pull request merged**
