### PR TITLE
Optimize aguaclara.play

### PR DESCRIPTION
**Pull request by oliver-leung**
I've made a few optimizations to the imports in `aguaclara.play`, and improved the documentation for Sphinx.

I've also (hopefully) resolved the strange issue of Python printing "`nparray`" a bunch of times when running `from aguaclara.play import *`. I'm not confident that it works for all machines yet, though -  @HannahSi , would you be able to try a local install of the package and see if you get those weird prints?

### CODE REVIEW

**Review by HannahSi — DISMISSED** [review]
Thank you for the optimizations and cleanups!

Strangely, I can't reproduce the "nparray" printing on my computer anymore, even with the old code in play.py. When I was testing the printing a few days ago though, I found that it was associated with importing three functions in headloss.py (note that "nparray" printed three times) that were wrapped with u.wraps() and ut.list_handler(). 
But since the printing is innocuous, it only happened on the first import of play.py, and it doesn't occur with the (old or) new code, I'd be alright with going ahead with the changes.

**Comment by eak24** [comment]
Why were the comments removed from play in this? Were they not helpful?

**Comment by oliver-leung** [comment]
I felt that they were a bit too verbose, especially the module docstring. Am I leaving out any important info?

**Comment by eak24** [comment]
@oliver-leung it's important that play is not used in the production code - I think leaving in an explanation that you shouldn't do that might be good.

**Comment by oliver-leung** [comment]
Got it, I'll add that!

**Pull request merged**
