### PR TITLE
Updates to procoda_parser.py and Pipfile.lock

### PR DESCRIPTION
**Pull request by HannahSi**
I updated a function and a few specifications in procoda_parser.py and updated Pipfile.lock to have the 2.20.0 version of the requests package.

### CODE REVIEW

**Review by oliver-leung — COMMENTED** [review]
This looks great! CodeCov says that some functions aren't covered, and I see that you added some new spreadsheets with test data. Are you planning on writing tests for those functions that manipulate the spreadsheets, or are they difficult to test?

Also, I see that some of the functions are quite long - in the future, I'd suggest breaking it up in to smaller helper functions so that it's easier to abstractly think of the code when developing. For example,

```python
# get the start and end times for the state
state_start_idx = states[:, 1] == state
state_start = states[state_start_idx, 0]  # gives a list of all the start times that day
state_end_idx = np.append([False], state_start_idx[0:-1])
state_end = states[state_end_idx, 0]  # gives a list of all the end times that day
```

could be abstracted as a helper function `get_start_end_time()`. This would also be easier to test, as you'd be able to see exactly which processes/functions cause errors.

A good rule of thumb that I use is to make each function _20 lines or less_.

**Comment by HannahSi** [comment]
Thanks for reviewing everything! Yes, I was planning to write tests using the spreadsheets--I used them for my own testing but was short on time in including full testing files (it is feasible). If it would be best to include them with the release, I'll try to write them tonight. 

You're right, the functions are very long. Would it be ok to make the task of breaking them up a task for the next release?

**Review by oliver-leung — DISMISSED** [review]
Yup, it's fine if you want to put those in the next release! I'll approve the PR, so merge when you'd like.

**Comment by HannahSi** [comment]
Sounds good, thanks again!

**Review by oliver-leung — APPROVED** [review]

**Pull request merged**
