### PR TITLE
Sedimentation tank design code

### PR DESCRIPTION
**Pull request by oliver-leung**
We're implementing design code to create a Sedimentation tank, as well as its associated tests and documentation.

### CODE REVIEW

**Comment by oliver-leung** [comment]
The function for calculating the inner diameter of the exit manifold (`sed_tank.ID_exit_man`) was incomplete, so I found [here](https://github.com/monroews/CEE4520_TA/blob/master/2017/Markdown/DC_Sedimentation_Solution.md) that that value is simply flow divided by upflow velocity in the sedimentation tank.

@monroews @ethan92429 @fletchapin I have a few questions on that:

1. Is that a safe way to calculate the exit manifold's inner diameter?
1. Should we worry about whether a pipe of some diameter exists as a standard size?
1. Does it make more sense to call it the "launder" or the "exit manifold"?

**Comment by monroews** [comment]
The exit launder design is more complicated.  I'd like to review the mathcad design. I think we limited manifold headloss to about 1 cm and the fundamental constraint was flow distribution

**Comment by fletchapin** [comment]
1) I don't access to that repo so not sure, but I think Monroe can answer this once he reviews the design
2) I think this would be a good idea. Monroe would have a better idea on the specifics, but for example in ```w_diffuser_inner``` has the following:
```return ut.ceil_nearest(w_diffuser_inner_min(sed_inputs).magnitude (np.arange(1/16,1/4,1/16)*u.inch).magnitude)```
3) I believe Zoe and I changed the name from "Launder" to "Exit Manifold" because we felt that keeping it consistent with "Entrance Manifold" was best

**Comment by oliver-leung** [comment]
I just found #39 , in which @monroews said that "NS.SedLaunder is calculated using NS.Manifold that is in the fluids functions". I also found that `physchem.py` has a `headloss_manifold()` function, which looks very similar to the existing code in `ID_exit_man()`. We could use that function to guess-and-check over a desired head loss of 1 cm.

However, I want to try to avoid using that strategy and calculate this diameter more explicitly. Does there already exist an equation to calculate manifold diameter from a desired head loss?

**Comment by monroews** [comment]
I checked in the Mathcad design files which are pretty easy to trace code!

Here is the line of code used to calculate the nominal diameter of the exit manifold

image

The pipe manifold equations were in the fluids functions. This should now be in physchem. 
image

**Comment by oliver-leung** [comment]
@monroews I have a few questions about the manifold equations:
- How should we specify the pressure recovery's maximum (PR_{max})? Should that be a constant, a function, or an expert input?
- What does PS_default mean, and should it be a constant, a function, or an expert input?

**Comment by monroews** [comment]
Which manifold diameter is designed using the pressure recovery constraint? I know we use this in the filter, as a constraint on the diameters of trunk and branch pipes. I can't recall using this is the sed tank. The pressure recovery constraint will need another pressure to make a dimensionless ratio that can then become the expert input. 

PS_default was the default pipe schedule. I believe we need this in order to be able to select the correct nominal pipe diameter. I assume the python hydraulic code will pass a nominal diameter and schedule for pipes to Onshape. Is that correct? Or does Onshape template assume a pipe schedule?

I'd love to have @ethan92429 's insight on whether Python or Onshape makes the decision about which pipe schedule to use.

**Comment by ksyselena1** [comment]
Added functions to sed_tank_bay and removed some functions from sed_tank. 
I am currently working on writing up the correct specifications for the docstring for both sed_tank_bay and sed_tank.

**Comment by ksyselena1** [comment]
I have finished up the docstring for class sedimentation tank bay and sedimentation tank and their corresponding init functions. I will now be working on testing sedimentation tank bay.

**Comment by oliver-leung** [comment]
Made a few changes to names to make them more intuitive, added better documentation, and fixed some broken variable/function references.

**Comment by ksyselena1** [comment]
Implemented and passed test cases for 6 functions in sed_tank_bay. Still working on last 2 functions (ID_exit_man and D_exit_man_orifice). There seems to be an error within the code itself, so I am trying to debug it.

**Comment by ksyselena1** [comment]
@monroews I am having trouble implement the function for D_exit_manifold_orifice. I was wondering if you had the formula for calculating the diameter of the orifices in the exit manifold for the sedimentation tank.

**Comment by ksyselena1** [comment]
Completed the function to calculate internal diameter for the pipe given pressure and implemented and passed a test case for the function.

**Comment by monroews** [comment]
You can use the orifice function in physchem to size the orifices.

**Review by HannahSi — APPROVED** [review]

**Pull request merged**
