### PR TITLE
Az297/matplotlib

### PR DESCRIPTION
**Pull request by alicezha0**
Figured out that the setup.py file did not align with the pipfile. 

1. Changed the matplotlib version in setup to match that in pipfile. 
2. Updated version

### CODE REVIEW

**Review by oliver-leung — DISMISSED** [review]
Looks good, merge whenever you're ready! I just resolved a small merge conflict.

**Comment by HannahSi** [comment]
Thanks for helping out with this issue @oliver-leung! Before we release, should we also update Pipfile.lock? Currently, it still specifies the old Matplotlib version 3.0.3.

**Comment by oliver-leung** [comment]
Ah, good catch! @alicezha0, could you run `pipenv lock` in your local repo and then push the changes?

**Comment by HannahSi** [comment]
It looks like the newest versions of some dependencies, including Pandas and Matplotlib, don't support Python 3.5. Is it necessary for us to maintain this compatibility? Or could we possibly jump `aguaclara` to version 0.2.0 and only support Python 3.6 and higher?

**Comment by HannahSi** [comment]
By the way @alicezha0, the Pipfile.lock changes look good!

**Comment by oliver-leung** [comment]
Since we know that the majority of our users are on Colab with Python 3.6, we can remove anything that specifies 3.5. Go through each of the configuration files in the top level directory and remove any mentions of 3.5.

**Comment by alicezha0** [comment]
I removed a mention of Python 3.5 from appveyor.yml from the top level directory of the package. I also incremented the release to 0.2.0 for this move away from Python 3.5.

**Comment by HannahSi** [comment]
Nice, but I think you'll need to remove 3.5 from the .travis.yml file too: https://github.com/AguaClara/aguaclara/blob/484ba9efd099070847a7efa360322ce7bb20f110/.travis.yml#L3-L5

**Review by HannahSi — APPROVED** [review]
Looks great!

**Pull request merged**
