### PR TITLE
fix Gran extract data function

### PR DESCRIPTION
**Pull request by monroews**

### CODE REVIEW

**Comment by HannahSi** [comment]
Does the argument `header=-1` cause an error? It appears that the `pandas.read_csv()` documentation recommends `header=None`, but the two arguments seem to work in the same way for me.

**Comment by monroews** [comment]
@HannahSi The function to read the data from the Gran data file created by ProCoDA was returning an error with the header=-1 notation. The error said it needed to be header = none. I'm not sure why this would happen, but the fix is easy.

**Comment by monroews** [comment]
Below is the error that I get when I use header=-1
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-13865477c380> in <module>()
     30     return Gran
     31 
---> 32 V_titrant, pH, V_sample, Normality_Titrant, V_equivalent, ANC = Gran(Gran_data)

6 frames
/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py in __init__(self, kwds)
   1435         elif self.header is not None and self.header < 0:
   1436             raise ValueError(
-> 1437                 "Passing negative integer to header is invalid. "
   1438                 "For no header, use header=None instead"
   1439             )

ValueError: Passing negative integer to header is invalid. For no header, use header=None instead

**Comment by HannahSi** [comment]
I see, thank you for providing the error traceback. I must have a version of Pandas that does not have the same error handling, but I'll approve this change to follow the documentation and accommodate the different version!

**Review by HannahSi — DISMISSED** [review]

**Comment by HannahSi** [comment]
@monroews one more thing, would you like this change to be released immediately as a new version? If so, I can increment the version number in setup.py.

**Comment by monroews** [comment]
An immediate release would be awesome.

**Review by HannahSi — APPROVED** [review]

**Comment by HannahSi** [comment]
All done!

**Pull request merged**
