### PR TITLE
max and min functions for NumPy arrays and Pint quantities

### PR DESCRIPTION
**Pull request by sc2267**
Implementation of #185 - adding Max and min functions

### CODE REVIEW

**Comment by sc2267** [comment]
Max function completed, working on min function now

**Comment by sc2267** [comment]
Update: Done writing code for max and min functions, just need to implement test functions for both to ensure they are correct.

**Comment by sc2267** [comment]
Still finishing up testing, couple errors in the code, needs debugging. Will be done before spring break

**Comment by sc2267** [comment]
Completed writing max and min functions, and wrote tests for both as well. All tests passed. Pushed commits to utility branch. Waiting for approval for merge into master

**Comment by oliver-leung** [comment]
Travis should pass once changes from #175 are incorporated into master.

**Review by oliver-leung — APPROVED** [review]

**Pull request merged**
